management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      actuator:
        enabled: true
      default-filters:
        - AddResponseHeader=X-GATEWAY, crypto-bot-gateway
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

  main:
    web-application-type: reactive

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


jwt:
  secret: M4rrE9sfhX9bPqLmX8vA2sW7kLpN3dQzCvKbMvUtXzWsUrYpPtHsVkTsGcXqFrZuF



