spring:
  rabbitmq:
    host: custom-rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: notification-api
  datasource:
    url: jdbc:postgresql://custom-postgres:5432/cryptobot_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8085

logging:
  level:
    root: INFO


telegram:
  bot-token: 8086521677:AAG4OBuQ6bhz9c6h2mLT6l-TNRfdYaOcuJM


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


binance:
  testnet-api-url: https://testnet.binance.vision/api
  production-api-url: https://api.binance.com/api
  stream-url: wss://stream.testnet.binance.vision/ws
  testnet-api-key: fPWYmJ0m9A3az7LRY9n9CemUgfZFbfxs89gAY8dAmpEniIfjAHqq1lrBKK4FYlk6
  testnet-secret-key: tbxVqviaGc1IOxdopn9Y8nzRuUHu1wyputtmnIt9w7ca96mrxK91nvjrSjgBfRKE
  production-api-key: OE00JQKAc6gLt4EpEDahpJrSffAl2RdwuPV5fO0XaurzBCmZ00m0UDtLZEaTucNP
  production-secret-key: OGu5l24wWvvD9vRcSaQhw7BOH3wKP5dlE7AXkQ2bryDXMmXWI7DGJVVYYSxgOFFr
  symbol: BTCUSDT
  profitability: 1.1
