spring:
  datasource:
    url: jdbc:postgresql://custom-postgres:5432/cryptobot_test
    username: postgres
    password: postgres
  rabbitmq:
    host: custom-rabbitmq
    port: 5672
    username: guest
    password: guest