spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085

logging:
  level:
    root: INFO


telegram:
  bot-token: 8086521677:AAG4OBuQ6bhz9c6h2mLT6l-TNRfdYaOcuJM


whatsapp:
  api-key: 7634858
