binance:
  api-url: https://api.binance.com/api
  stream-url: wss://stream.binance.com:9443/ws
  api-key: OE00JQKAc6gLt4EpEDahpJrSffAl2RdwuPV5fO0XaurzBCmZ00m0UDtLZEaTucNP
  secret-key: OGu5l24wWvvD9vRcSaQhw7BOH3wKP5dlE7AXkQ2bryDXMmXWI7DGJVVYYSxgOFFr
  symbol: BTCUSDT
  profitability: 1.1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptobot_prod
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
