server:
  port: 8888

spring:
  application:
    name: config-api

  cloud:
    config:
      server:
        git:
          uri: https://github.com/seu-usuario/seu-repo-configs
          default-label: main
          search-paths: config
          username: seu-usuario
          password: sua-senha-ou-token

management:
  endpoints:
    web:
      exposure:
        include: "*"
