spring:
  profiles:
    active: dev
  application:
    name: futures-api

server:
  port: 8084

logging:
  level:
    root: INFO

jwt:
  secret: a7Zml3kERUdv1tG64g2W9D3rCu8FvXy98lM5aDhzVPVb9BzRkK28PmQdUqU5YQzX

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true