spring:
  profiles:
    active: dev
  application:
    name: auth-api

server:
  port: 8081

logging:
  level:
    root: INFO

jwt:
  secret: M4rrE9sfhX9bPqLmX8vA2sW7kLpN3dQzCvKbMvUtXzWsUrYpPtHsVkTsGcXqFrZuF


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true