server:
  port: 8086

management:
  profiles:
    active: dev
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

webclient:
  timeout:
    connect: 5000
    read: 5000


strategy-api:
  url: http://localhost:8083

spring:
  application:
    name: scheduler-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptobot_test
    username: postgres
    password: postgres

logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: DEBUG

